services:
  - type: web
    name: edgecom
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn edgecom.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com