# Generated by Django 6.0.5 on 2026-06-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rfc', models.CharField(max_length=13)),
                ('regimen_fiscal', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('codigo_postal', models.CharField(max_length=5)),
                ('telefono', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('sitio_web', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracion/')),
                ('pie_pagina', models.TextField(blank=True, null=True)),
                ('color_primario', models.CharField(default='#1a5276', max_length=7)),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
            },
        ),
    ]
