# Generated by Django 6.0.5 on 2026-06-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0002_agente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
