# Generated by Django 6.0.5 on 2026-05-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
