# Generated by Django 6.0.5 on 2026-06-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_contacto_notas_alter_contacto_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='tipo',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor')], default='CLIENTE', max_length=10),
        ),
    ]
