# Generated by Django 6.0.5 on 2026-05-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('clabe', models.CharField(max_length=18)),
                ('beneficiario', models.CharField(max_length=200)),
                ('moneda', models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', max_length=3)),
            ],
        ),
    ]
