# Generated by Django 6.0.5 on 2026-06-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_rol_puede_ver_catalogo_rol_puede_ver_agentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='puede_ver_compras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_ver_proveedores',
            field=models.BooleanField(default=False),
        ),
    ]
