# Generated by Django 6.0.5 on 2026-05-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('clave_sat', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('unidad_sat', models.CharField(max_length=50)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
