# Generated by Django 6.0.5 on 2026-05-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rfc', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=200)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('regimen_fiscal', models.CharField(max_length=100)),
            ],
        ),
    ]
