# Generated by Django 6.0.5 on 2026-05-13 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('folio', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('NEGOCIACION', 'Negociación'), ('PERDIDO', 'Perdido'), ('FACTURADO', 'Facturado')], max_length=12)),
                ('rfc', models.ForeignKey(db_column='rfc', on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
