# Generated by Django 6.0.5 on 2026-05-17 04:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
