# Generated by Django 6.0.5 on 2026-05-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_alter_cotizacion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
