# Generated by Django 6.0.5 on 2026-05-20 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0001_initial'),
        ('cotizaciones', '0005_detallecotizacion'),
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentes.agente'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directorio.contacto'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('ANTICIPADO', 'Por anticipado al recibir orden de compra'), ('ANTICIPO_25', 'Se requiere anticipo 25%'), ('ANTICIPO_50', 'Se requiere anticipo 50%'), ('ANTICIPO_75', 'Se requiere anticipo 75%'), ('CONTRA_ENTREGA', 'Contra entrega'), ('CONTRA_EMBARQUE', 'Contra aviso de embarque'), ('CREDITO_15', 'Crédito 15 días'), ('CREDITO_30', 'Crédito 30 días'), ('CREDITO_60', 'Crédito 60 días'), ('CREDITO_90', 'Crédito 90 días')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='iva',
            field=models.CharField(choices=[('0', '0%'), ('8', '8%'), ('16', '16%')], default='16', max_length=2),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='lugar_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='moneda',
            field=models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', max_length=3),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='solicitud',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tiempo_entrega',
            field=models.CharField(blank=True, choices=[('3', '3 días'), ('5', '5 días'), ('7', '7 días'), ('10', '10 días'), ('2S', '2 semanas'), ('4S', '4 semanas'), ('6S', '6 semanas'), ('8S', '8 semanas'), ('12S', '12 semanas')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vigencia',
            field=models.CharField(blank=True, choices=[('10', '10 días'), ('30', '30 días'), ('60', '60 días')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
