# Generated by Django 6.0.5 on 2026-05-20 02:13

import cotizaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_cotizacion_agente_cotizacion_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='folio',
            field=models.CharField(default=cotizaciones.models.generar_folio, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
