# Generated by Django 6.0.5 on 2026-05-23 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('cotizaciones', '0007_alter_cotizacion_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='iva',
            field=models.CharField(blank=True, choices=[('0', '0%'), ('8', '8%'), ('16', '16%')], default='16', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='moneda',
            field=models.CharField(blank=True, choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='rfc',
            field=models.ForeignKey(blank=True, db_column='rfc', null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='status',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('NEGOCIACION', 'Negociación'), ('PERDIDO', 'Perdido'), ('FACTURADO', 'Facturado')], max_length=12, null=True),
        ),
    ]
