# Generated by Django 6.0.5 on 2026-07-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0010_cotizacion_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
