# Generated by Django 6.0.5 on 2026-07-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0011_cotizacion_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
