# Generated by Django 6.0.5 on 2026-07-30 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        ('cotizaciones', '0012_cotizacion_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='configuracion.configuracionempresa', verbose_name='Empresa emisora'),
        ),
    ]
