# Generated by Django 6.0.5 on 2026-08-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0013_cotizacion_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecotizacion',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
