# Generated by Django 6.0.5 on 2026-05-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='monto_abono',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='status',
            field=models.CharField(choices=[('TIMBRADO', 'Timbrado'), ('PAGADO', 'Pagado'), ('CREDITO', 'Crédito'), ('ADEUDO', 'Adeudo'), ('ABONO', 'Abono')], max_length=10),
        ),
    ]
