# Generated by Django 6.0.5 on 2026-05-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_factura_fecha_vencimiento_factura_monto_abono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
