# Generated by Django 6.0.5 on 2026-05-25 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0001_initial'),
        ('facturas', '0004_factura_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='agentes.agente'),
        ),
    ]
