# Generated by Django 6.0.5 on 2026-06-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0005_factura_agente'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago / Abono'),
        ),
    ]
