# Generated by Django 6.0.5 on 2026-06-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0006_factura_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
