# Generated by Django 6.0.5 on 2026-07-13 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0007_factura_fecha_creacion'),
        ('productos', '0002_producto_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='facturama_id',
            field=models.CharField(blank=True, help_text='ID único en Facturama', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='forma_pago',
            field=models.CharField(default='03', help_text='Ej: 03=Transferencia, 01=Efectivo', max_length=2),
        ),
        migrations.AddField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(default='PUE', help_text='PUE (Una sola exhibición) o PPD (Parcialidades)', max_length=3),
        ),
        migrations.AddField(
            model_name='factura',
            name='pdf_sat',
            field=models.FileField(blank=True, null=True, upload_to='facturas_sat/pdf/'),
        ),
        migrations.AddField(
            model_name='factura',
            name='uso_cfdi',
            field=models.CharField(default='G03', help_text='Ej: G03=Gastos en general, DE01=Gastos médicos', max_length=3),
        ),
        migrations.AddField(
            model_name='factura',
            name='uuid',
            field=models.CharField(blank=True, help_text='Folio Fiscal otorgado por el SAT', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='xml_sat',
            field=models.FileField(blank=True, null=True, upload_to='facturas_sat/xml/'),
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturas.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
        ),
    ]
