# Generated by Django 6.0.5 on 2026-07-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0008_factura_facturama_id_factura_forma_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='objeto_impuesto',
            field=models.CharField(default='02', help_text='02 = Sí objeto de impuesto', max_length=2),
        ),
    ]
