# Generated by Django 6.0.5 on 2026-07-14 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0009_detallefactura_objeto_impuesto'),
        ('productos', '0002_producto_fecha_creacion'),
        ('servicios', '0002_servicio_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicios.servicio'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
    ]
