# Generated by Django 6.0.5 on 2026-07-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0010_detallefactura_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='forma_pago',
            field=models.CharField(choices=[('01', '[01] Efectivo'), ('02', '[02] Cheque nominativo'), ('03', '[03] Transferencia electrónica de fondos'), ('04', '[04] Tarjeta de crédito'), ('28', '[28] Tarjeta de débito'), ('99', '[99] Por definir')], default='03', help_text='Ej: 03=Transferencia, 01=Efectivo', max_length=2),
        ),
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(choices=[('PUE', '[PUE] Pago en una sola exhibición'), ('PPD', '[PPD] Pago en parcialidades o diferido')], default='PUE', help_text='PUE (Una sola exhibición) o PPD (Parcialidades)', max_length=3),
        ),
        migrations.AlterField(
            model_name='factura',
            name='uso_cfdi',
            field=models.CharField(choices=[('G01', '[G01] Adquisición de mercancías'), ('G03', '[G03] Gastos en general'), ('I01', '[I01] Construcciones'), ('I04', '[I04] Equipo de cómputo y accesorios'), ('S01', '[S01] Sin efectos fiscales'), ('CP01', '[CP01] Pagos')], default='G03', help_text='Ej: G03=Gastos en general, DE01=Gastos médicos', max_length=4),
        ),
    ]
