# Generated by Django 6.0.5 on 2026-07-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0011_alter_factura_forma_pago_alter_factura_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='forma_pago',
            field=models.CharField(default='03', help_text='Ej: 03=Transferencia, 01=Efectivo', max_length=2),
        ),
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(default='PUE', help_text='PUE (Una sola exhibición) o PPD (Parcialidades)', max_length=3),
        ),
        migrations.AlterField(
            model_name='factura',
            name='uso_cfdi',
            field=models.CharField(default='G03', help_text='Ej: G03=Gastos en general, DE01=Gastos médicos', max_length=4),
        ),
    ]
