# Generated by Django 6.0.5 on 2026-07-30 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        ('facturas', '0012_alter_factura_forma_pago_alter_factura_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='configuracion.configuracionempresa', verbose_name='Empresa emisora'),
        ),
    ]
