# Generated by Django 6.0.5 on 2026-06-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago / Abono'),
        ),
        migrations.AddField(
            model_name='compra',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito')], max_length=15, null=True),
        ),
    ]
