# Generated by Django 6.0.5 on 2026-06-16 04:55

import compras.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_fecha_pago_compra_forma_pago'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('folio_orden', models.CharField(default=compras.models.generar_folio_orden, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('folio_cotizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('forma_pago', models.CharField(blank=True, choices=[('TRANSFERENCIA', 'Transferencia'), ('CREDITO', 'Crédito'), ('DEBITO', 'Débito'), ('EFECTIVO', 'Efectivo')], max_length=15, null=True)),
                ('moneda', models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', max_length=3)),
                ('cotizacion_interna', models.TextField(blank=True, null=True)),
                ('numero_pedido_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='proveedores.proveedor')),
                ('usuario_solicita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ordencompra')),
            ],
        ),
    ]
