# Generated by Django 6.0.5 on 2026-07-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_ordencompra_detalleordencompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
